# Generated by Django 5.2.7 on 2025-10-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_license', '0002_remove_product_product_id_product_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botlicense',
            name='activated',
        ),
        migrations.RemoveField(
            model_name='botlicense',
            name='hwid',
        ),
        migrations.AlterField(
            model_name='botlicense',
            name='account_id',
            field=models.CharField(max_length=25),
        ),
    ]
