# Generated by Django 5.2.7 on 2025-10-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_license', '0003_remove_botlicense_activated_remove_botlicense_hwid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botlicense',
            name='license_key',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
