# Generated by Django 5.2.7 on 2025-10-31 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_license', '0004_alter_botlicense_license_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botlicense',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
